#!/bin/sh

# Exit immediately if a simple command exits with a nonzero exit value
set -e

# Cleanup
rm -rf output

# Build the Docker image
docker build -t goimage .

# Generate the app generated by using go build
docker-compose run --rm generate1

# Generate the app generated by using go build without so.mod and go.sum
docker-compose run --rm generate2

# Compare the two apps. This will print their respective SHA1 checksums
docker-compose run --rm compare
